### ISSUE TITLE
Error: "Unable to load categories data: auto"

### ISSUE THREAD

**Issue by aurelberra** [voyanttools/Voyant#10]
Many thanks for all the recent work! It's wonderful to see Voyant Tools is maintained – and further developed.

Speaking of new developments, I know that categories are an experimental feature. You probably are aware that an error pops up on loading most corpora, but I thought I should mention that here. I'm happy to help with testing if needed.

<img width="314" alt="Screenshot 2022-01-19 at 10 45 57" src="https://user-images.githubusercontent.com/1230441/150106434-c223bbb4-2cc1-4666-9c43-a1d4f0852b83.png">

**Comment by ajmacdonald** [comment]
Thanks for your kind words Aurélien.
I would very much appreciate your help with this. I will send you an email.

**Comment by aurelberra** [comment]
Thank you. Reply sent. Hope it helps!

**Comment by ajmacdonald** [comment]
Fixed by https://github.com/voyanttools/trombone/commit/f8aff671eee48fb34b5391398fe5df989a3ba57d#diff-749fcbbb2a833efa89642ac47a05cddabc5cf727f19d451e5defb9f82b7b01d3 but was still present on an older mirror of the site.
