### ISSUE TITLE
Template parser breaks on single quotation marks

### ISSUE THREAD

**Issue by chafikamr** [voyanttools/Voyant#100]
when you **add a new document to documents list**, you cannot **remove** one of them , it shows an **error in the console**

![image](https://github.com/voyanttools/Voyant/assets/71721086/a66f162b-e619-414f-8c60-ecd74a4be31e)
![image](https://github.com/voyanttools/Voyant/assets/71721086/03895fef-b81f-420f-a9f3-806f55f8ccbc)

**Comment by ajmacdonald** [comment]
Thanks for reporting this bug. Unfortunately I'm having trouble reproducing it. Could you please outline exactly what steps you're taking?
Also it looks like the one document has 0 text content. That shouldn't have an effect but it is a bit odd.

**Comment by chafikamr** [comment]
[recording.webm](https://github.com/voyanttools/Voyant/assets/71721086/b96c6d0e-1711-4171-b8a3-a711969af946)

**Comment by chafikamr** [comment]
> Thanks for reporting this bug. Unfortunately I'm having trouble reproducing it. Could you please outline exactly what steps you're taking? Also it looks like the one document has 0 text content. That shouldn't have an effect but it is a bit odd.
the document that has 0 text is for testig purposes only, this happend with all documents

**Comment by ajmacdonald** [comment]
Thank you for the video.
I've located the issue and it has to do with single quotation marks in the French localization.
Until I publish a fix, a workaround would be to use the English localization.

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/12a245c63cc3dff3fbfdb0afe9dd86418eea2c4d
