### ISSUE TITLE
Visual language for Voyant 

### ISSUE THREAD

**Issue by janisdd** [voyanttools/Voyant#107]
Hi there,

It seems that the Voyant consortium is still in its early days and I'm not sure what the roadmap is or how to get involved...

That being said, I talked to Geoffrey at DH2024 about implementing something like a visual language for Voyant (with nodes, edges and data flow, something like https://orangedatamining.com/) and he seems open to the idea.

That being said, I've been talking to Geoffrey at DH2024 about implementing some kind of visual language for Voyant (with nodes, edges and data flow, something like https://orangedatamining.com/), and he seemed open to the idea.

I think it could be implemented separately like Spyral without affecting the rest of the system, but I still need to take a closer look at the code.

The first step I took was to run Voyant locally. I tried to use the documentation at https://github.com/voyanttools/Voyant/wiki/Eclipse-Workspace-Setup, but I mainly use IntelliJ and had difficulties getting it to work. In the end, however, it worked.

I will create a tutorial (Markdown file) with the steps to install Voyant with Intellij.

So my first question is: can we insert the tutorial here somewhere when I have finished it?

Second question: I plan to look at the code to get a better understanding of the entire system. Is there any documentation about the system from a technical point of view? 
Third question: To familiarize myself with the system, I would like to look at the problems and see if I can solve some. How open are you to pull requests?

Last question: My final goal is to implement the visual language. As there will be some questions and discussions, can you enable the discussion feature of this repository (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository)? It may better to discuss things there instead of creating issues.

Last question: my ultimate goal is to implement the visual language. Since there will be some questions and discussions, can you enable the discussion feature of this repository (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository)? It might be better to discuss things there rather than creating issues.

**Comment by ajmacdonald** [comment]
Hello!
Thanks for your interest in adding to and expanding the functionality of Voyant!
To answer your questions:
1) Yes, I'll add it to the wiki.
2) Not really. If you email me at voyanttools @ gmail we could discuss it further.
3) Done: https://github.com/voyanttools/Voyant/discussions

**Comment by janisdd** [comment]
@ajmacdonald  I've created a guide to setup the project with IntelliJ (Ultimate). See the attached file.
[voyant_intellij_setup.md](https://github.com/user-attachments/files/17381326/voyant_intellij_setup.md)

If I am to add images, can you tell me how I can send you all the files? Simply upload a ZIP file in this issue?

**Comment by ajmacdonald** [comment]
I've started a discussion using your file as the base: https://github.com/voyanttools/Voyant/discussions/109
I modified the note about Java 11, the version of Tomcat, and the Github repo links.
Maybe you can reply to it with an updated version including the images? The discussions thing is new to me.
