### ISSUE TITLE
Spyral: Saved Notebooks Missing

### ISSUE THREAD

**Issue by centenarydh** [voyanttools/Voyant#108]
Spyral is unable to load saved notebooks, giving this error:

![image](https://github.com/user-attachments/assets/6e7ea6f6-96e7-42c1-bceb-1515a05a17d8)

This happens with recently completed notebooks by my students, past class notebooks, and my example notebooks. For example, this is my sample notebook for the class: https://voyant-tools.org/spyral/centenarydh@gh/UQxUKI/. I also noticed that nothing comes up in the catalogue. 

Has there been a server change? Are the notebooks recoverable?

**Comment by ajmacdonald** [comment]
Apologies. There was an issue with the server around Oct 13-14th that may have affected notebooks created at that time. It's been resolved and you should be able to access your notebooks now (including the one you linked). Please let me know if that's not the case.
