### ISSUE TITLE
Error: Unable to load corpus

### ISSUE THREAD

**Issue by BerardiGiulia** [voyanttools/Voyant#11]
Hi, when trying to upload a corpus, I get the following error
<img width="898" alt="error_Voyant" src="https://user-images.githubusercontent.com/61156570/150323870-86746868-1778-410c-a4dd-4c55ec839e38.png">

**Comment by ajmacdonald** [comment]
Apologies for the ongoing issues with the server. You should be able to upload again.
I'm working hard to implement a long term fix.
