### ISSUE TITLE
Spyral: Firefox thinks Spyral pages are in French when they are not

### ISSUE THREAD

**Issue by johnBradley501** [voyanttools/Voyant#112]
Firefox seems to think that a Spyral page is in French even when it isn't.  See attached screenshot for what happens.
![Spyral-French](https://github.com/user-attachments/assets/f77db95a-2265-41cb-8ebb-e38d175aaead)

Getting this screen regularly is a nuisance, and worth tackling the code behind it to see if it can be fixed.

**Comment by ajmacdonald** [comment]
Note to self: add the lang attribute to html tag, populated by the currently selected Voyant translation.

**Comment by ajmacdonald** [comment]
Fixed: https://github.com/voyanttools/Voyant/commit/144067ee3b84c7b1bc4a5721898457694dec2237
