### ISSUE TITLE
Corpus tools versus Document tools

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/Voyant#18]
When selecting a document item in a list displays the trend five terms relative to the multi-document corpus five most frequent terms. Thus my assumption is that the individual document view is best examined as a single document corpus for displaying cirrus and trends unique to the document.

Is there a way to display document cirrus and trends unique to the selected document item in a multi-document corpus?

**Comment by ajmacdonald** [comment]
Some tools have a Scale button that allow you to specify documents
![image](https://user-images.githubusercontent.com/882444/163419872-c5562e0c-ca24-413f-895e-325264b17bf7.png)

**Comment by pbstudent** [comment]
Thank you for the illustration. Note that the grey dot does not move to the active line item, nor is the document title given in panel footer for context.

What is the difference between Corpus Tools > Cirrus and Document Tools  and Document Tools > Cirrus ?

The tools panels interact with other panels in different ways such as selecting a Documents item changes the focus on Trends and Collocates but not Cirrus. There appears to be a _corpus_ display and a _documents_ display only for certain panels; however when selecting a document, panels such as Trends displays Corpus per document context whereas collocates displays a document context. Thus knowing the context of each panel is critical. What is extremely useful with VoyantTools is its all-in-one Corpus/Documents contexts screen having the ability to work on individual documents or all documents without needing to start over from the corpus creation screen for a single document view.

Noteworthy (as per your illustration), there is document context selection for Cirrus but not in Trends.

Some icon or colour indicator of which context for each panel (e.g., C, D, C/D) may be helpful cue?

**Comment by ajmacdonald** [comment]
> What is the difference between Corpus Tools > Cirrus and Document Tools and Document Tools > Cirrus ?

There is no difference. Tools that work at the corpus level are listed under Corpus Tools and tools that work at the document level are listed under Document Tools. There is some overlap between the two.

**Comment by pbstudent** [comment]
It would be useful and consistent for interactive updates between document or corpus choices across all panels rather than one way for graphics, and another for texts for individual document views.
