### ISSUE TITLE
Correlations for Document Tools

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/Voyant#21]
Current list for Document Tools does not include Correlations:
<img width="291" alt="doc-menu" src="https://user-images.githubusercontent.com/24277755/165459800-c32a5d48-413b-4c93-8eb9-e91722895a54.png">

The workaround is to take each document from the multi-document corpus and start over with a single document corpus analysis. I would like to understand why Correlations was not included in the Document Tools section of a multi-document corpus when it is displayed in a single document corpus.

**Comment by ajmacdonald** [comment]
When you're working with a multi document corpus you can use the Scale button in the Correlations tool to filter which document(s) gets analyzed.

I can't speak as to why the tool is in the list of Corpus Tools and not in the list of Document Tools.
