### ISSUE TITLE
Trends Data enhancement wish

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/Voyant#23]
Currently Trends produces a visualization. However, it does not have an export option to download a CSV text of the data that produced the line+stacked bar. There is an option to export view but not the data that produced the visualization. Reproducing the visualization from data within LibreOffice spreadsheet could be advantageous to developing custom presentations.

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/9279c11b1a5ea9c3698a92bf5ca15303fe29d283
