### ISSUE TITLE
Voyant Tools Bibliographic Reference Permalink

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/Voyant#24]
For how long is a bibliographic URL from [Voyant-Tools](https://voyant-tools.org/) active online?

**Comment by ajmacdonald** [comment]
Hi pbstudent,
If you have general questions about Voyant, please feel free to email me at voyanttools@gmail.com
To answer this question, we aim to have corpora persist for as long as possible but there are no guarantees of data retention.
