### ISSUE TITLE
Options not displaying maximum terms

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/Voyant#29]
https://voyant-tools.org/docs/#!/guide/cirrus
states that options includes Maximum terms, however this is the display:
![Screenshot 2022-07-25 at 19-28-39 Cirrus - Voyant Tools Help](https://user-images.githubusercontent.com/24277755/180838902-e08f0133-856a-4c77-a6e0-b234e808cc71.png)

I am unsure what the default setting is... 55, 50 ?

**Comment by ajmacdonald** [comment]
Thanks for finding this.
I believe that that options text in the guide was either copy/pasted, or the options dialog has changed since it was written.

The default value for Terms is 50.

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/981953a46754066388fd8a9e6208bc9ab03aa344
