### ISSUE TITLE
Bibliographic reference differences when using search syntax

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/Voyant#30]
Exporting bibliographic reference can give different results in URL depending on the way you retrieve the reference when using a particular search syntax.

Export from panel:

Sinclair, S. & G. Rockwell. (2022). Contexts. Voyant Tools. Retrieved August 11, 2022, from https://voyant-tools.org/?query=%5Elicense*&corpus=7aa35badfd701d1e930570cf06da5eab&view=Contexts

Export to window from panel:

Sinclair, S. & G. Rockwell. (2022). Contexts. Voyant Tools. Retrieved August 11, 2022, from https://voyant-tools.org/?view=Contexts&query=license&corpus=7aa35badfd701d1e930570cf06da5eab

**Comment by ajmacdonald** [comment]
I see that the query and view parameters are in a different order. Functionally the URL is the same however.

The parameters are drawn from an object and so the order is not guaranteed to be consistent (like in an array).

**Comment by pbstudent** [comment]
Same content different URL
