### ISSUE TITLE
Contexts reading of bullets changed

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/Voyant#31]
bullet interpreted as ¥

Sinclair, S. & G. Rockwell. (2022). Contexts. Voyant Tools. Retrieved September 4, 2022, from https://voyant-tools.org/?query=resources&corpus=e44f6aba0a6c711b581e316dbff2ad0d&view=Contexts

services • identify human and other resources 
services ¥ identify human and other

**Comment by ajmacdonald** [comment]
That's odd. Can you please describe the file format and encoding of the source document (or email a copy to voyanttools @ gmail)?

**Comment by pbstudent** [comment]
Since the problem that you identified is that the plain text is encoded in ANSI instead of UTF-8, is there a way Voyant Tools could automatically recognize a plain text file and convert to UTF-8 ?
