### ISSUE TITLE
CLI or API support

### ISSUE THREAD

**Issue by sinanyalcinkaya** [voyanttools/Voyant#34]
Hello, I want to use voyant in command line I need basic functionalities (create/modify corpus) with cli or in script (javascript, python or bash). Spyral is awesome tools but I want to use it with cli/scripts. I found voyantjs project but I can't running it with npm install / npm run etc... Please write mini installation tutorial and commands examples. Thank you

**Comment by ajmacdonald** [comment]
Hello and thank you for your interest.

If you set up your own [local installation of Voyant](https://github.com/voyanttools/VoyantServer) you could then query it.

I don't really have the time to write out API docs but there is some info in the [Spyral docs for the Corpus class](https://voyant-tools.org/docs/#!/api/Spyral.Corpus).

To create a corpus programmatically, you'll need to send a GET request with the following:
- tool (string): `corpus.CorpusMetadata`
- input (string): the URL(s) or text(s) to ingest

For example: http://localhost:8080/trombone?tool=corpus.CorpusMetadata&input=The+quick+brown+fox+jumps+over+the+lazy+dog&input=Sphinx+of+black+quartz%2C+judge+my+vow

If the input is a file, you'll need to create [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) and use POST to submit that instead. Here is the related code that voyantjs uses to do that: https://github.com/voyanttools/voyantjs/blob/master/src/corpus.js#L1609-L1661

Spyral uses voyantjs and adds some additional functionality. If you're familiar with npm (and rollup) you can see where the build happens here: https://github.com/voyanttools/Voyant/blob/master/src/main/webapp/resources/spyral/package.json
