### ISSUE TITLE
Voyant Tools Trends Help

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/Voyant#36]
https://voyant-tools.org/docs/#!/guide/trends states:
"relative frequencies (default): term frequency in document or document segment"

Definition may need disambiguation...

Questions:
1. Frequency of term relative to what? Relative to corpus (i.e., term count in document / total term count in corpus)? However, this would not give the correct values.
According to https://voyant-tools.org/docs/#!/guide/corpusterms "relative frequency of the term in the corpus, per one million words"
(understanding calculation of relative frequency would be helpful)
2. Trends Help stated, "You can also select the frequency mode:  relative frequencies  or   raw frequencies"
How can I select raw instead of relative in the Trend display?

**Comment by ajmacdonald** [comment]
1. Relative to other terms in that document. The calculation is: (term count in document / total tokens in document) * 1000000
2. This can be done from the options menu.

**Comment by pbstudent** [comment]
May be helpful to have Options visual:
![Screenshot 2022-11-09 at 17-36-48 Voyant Tools](https://user-images.githubusercontent.com/24277755/200891988-c42652bf-8b16-4d12-a529-2fb55c068b7c.png)
or
<img width="619" alt="options (1)" src="https://user-images.githubusercontent.com/24277755/200894166-ac027521-0d3a-467e-9950-c1ffd1326736.png">




Note: https://voyant-tools.org/docs/#!/guide/trends appears to be disconnected from examples.

**Comment by pbstudent** [comment]
> 

What is the significance of 1000000?
