### ISSUE TITLE
Array of URLS

### ISSUE THREAD

**Issue by maartenpt** [voyanttools/Voyant#38]
According to main/webapp/app/data/model/Corpus.js  you should be able to provide an array of URLS:

`new Corpus(["http://hermeneuti.ca/", "https://en.wikipedia.org/wiki/Voyant_Tools"]); // two documents from URLs`

but if you attempt to do that via the URL to get an embedded viewer with not just one big text, but a corpus split into separate texts, TomCat gives an error complaining about invalid characters in the URL:

`https://voyant-tools.org/?input[0]=https://first.url&input[01]=https://second.url`

while for instance providing a comma-separated list only reads the last URL:

`https://voyant-tools.org/?input=https://first.url,https://second.url`

other options to attempt to load structured content, such as wrapping it in a teiCorpus with each document as a TEI element, or a single TEI element with multiple <text> nodes also do not work - the corpus it creates still only contains a single document. 

Is there no way to get a structured external document into Voyant using a URL?

**Comment by ajmacdonald** [comment]
Hello Maarten,

Yes, it is possible. You can use multiple sources by adding another input parameter, e.g.
`https://voyant-tools.org/?input=https://first.url&input=https://second.url`

This is also how other arrays of parameters are specified, e.g. https://voyant-tools.org/?corpus=austen&view=corpusterms&query=good&query=bad
