### ISSUE TITLE
Documentation on Self-Hosted Instance

### ISSUE THREAD

**Issue by myriadfront** [voyanttools/Voyant#4]
Hey @ajmacdonald. I was wondering if there is any documentation on self-hosting an instance of Voyant? I work for a company that makes what is primarily geospatial software for indigenous communities that links textual records like archival documents, interview transcripts, etc. with the map. In it, you can package a zip file of all the documents related to a spatial query. It would be really slick to get our software team to spin up an instance of Voyant that can receive the zip file, so instead of just downloading, it could be sent for qualitative analysis.  None of us are Java devs. I'm sure the actual developers on our team could figure it out, but I want to provide them whatever information I can before I make the request.  

We had a conversation going with Stefan in the past and we were really sorry to hear about his passing.  Voyant is incredible. Thanks for the amazing work of you and your team.

**Comment by ajmacdonald** [comment]
Hello @myriadfront 

Thank you for your kind words and for your interest in Voyant.
Unfortunately there isn't any documentation yet about self-hosting a networked instance, only about running a [local instance from a jar file](https://github.com/voyanttools/VoyantServer#installation).

That said, it shouldn't be too difficult to get it running. Our instance of Voyant is a servlet that runs via Tomcat, and can be installed by:

- downloading the latest [VoyantServer.zip](https://github.com/sgsinclair/VoyantServer/releases) and unzipping it
- copying the contents of the `_app` directory to `/var/lib/tomcat/webapps/ROOT`
- restarting the Tomcat service

Additionally, we make the following (optional) modifications to the `/etc/tomcat/tomcat.conf` file:

- change the Catalina temp directory to a custom one that Voyant uses for uploads, indexing, and caching results: `CATALINA_TMPDIR="/voyant-data"`
- modify the Java options to use more RAM and change how Voyant indexes corpora: `JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true -Xmx16g -XX:MaxPermSize=256m -XX:+UseConcMarkSweepGC -Dorg.voyanttools.server.storage=file-per-corpus"`

We also modify `/etc/tomcat/server.xml` to allow for larger uploads and ensure UTF-8 is used for encoding: `<Connector port="8080" protocol="HTTP/1.1" connectionTimeout="20000" maxPostSize="100000000" URIEncoding="UTF-8" redirectPort="8443" />` 

Alternately, if your team is familiar with Docker, work is being done on a [dockerized version of Voyant](https://gitlab.com/calincs/access/voyant-docker/).

**Comment by myriadfront** [comment]
Thank you so much, @ajmacdonald! I was trying to compile a JAR from the repository I downloaded here, but kept having issues with one of the Trombone files. Your method sounds much simpler. My knowledge of coding is pretty slim. HTML, JS, CSS. Only experience with Java was self-hosted Jira and Alfresco instances almost a decade ago. Thanks for helping this luddite out!  

I already have my Tomcat server up and running for this, so will try tonight.
