### ISSUE TITLE
Add MODS to bibliographic export options

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/Voyant#41]
Feature request

Currently the Voyant Tools APA reference is generated like this:

Sinclair, S. & G. Rockwell. (2022). Contexts. Voyant Tools. Retrieved November 22, 2022, from https://voyant-tools.org/?stopList=keywords-3bca001d92827d6323779fa9dad741e5&query=must&corpus=067ee494bb8319c530da25e2a6c177e4&view=Contexts

However, this does not translate easily to Zotero, which I believe is the best free open source citation management system with browser and office connectivity for students.

Is there a way to easily transpose Voyant Tools references to Zotero citation items? Furthermore, as per the aforementioned example, the inclusion of context term(s) would be more descriptive of the title (e.g., Contexts: Must).

References:
https://www.zotero.org/support/kb/importing_standardized_formats
https://github.com/aurimasv/translators/wiki/RIS-Tag-Map

P.S. ironically an addon in Zotero was designed to export to Voyant Tools (https://github.com/corajr/zotero-voyant-export/)

**Comment by ajmacdonald** [comment]
Modifying the title to include query terms opens a can of worms, however I can at least add MODS support.

Can you tell me if the following captures the info sufficiently for Zotero?
```
<mods version="3.4" xmlns="http://www.loc.gov/mods/v3">
	<titleInfo>
		<title>Contexts</title>
	</titleInfo>
	<relatedItem type="host">
		<titleInfo>
			<title>Voyant Tools</title>
		</titleInfo>
	</relatedItem>
	<name>
		<namePart>Sinclair, Stéfan</namePart>
		<role>
			<roleTerm type="code" authority="marcrelator">cre</roleTerm>
		</role>
	</name>
	<name>
		<namePart>Rockwell, Geoffrey</namePart>
		<role>
			<roleTerm type="code" authority="marcrelator">cre</roleTerm>
		</role>
	</name>
	<relatedItem displayLabel="URL" type="constituent">
		<identifier typeURI="https://voyant-tools.org/?stopList=keywords-3bca001d92827d6323779fa9dad741e5&amp;query=must&amp;corpus=067ee494bb8319c530da25e2a6c177e4&amp;view=Contexts"/>
		<originInfo>
			<dateCaptured encoding="iso8601">20221123</dateCaptured>
		</originInfo>
	</relatedItem>
	<genre>website</genre>
	<physicalDescription>
		<form>electronic</form>
		<internetMediaType>text/html</internetMediaType>
		<digitalOrigin>born digital</digitalOrigin>
	</physicalDescription>
</mods>
```

Since the URL includes ampersands I have to convert them to `&amp;` in order for the XML to well formed, however this means the link isn't accurate. I'm not sure what the right solution is.

**Comment by pbstudent** [comment]
The ideal functionality would be to have any Voyant-Tools webpage in native Zotero format that would automatically be recognized by the Zotero web browser connector. Alternatively an RIS file or MODS open format. Perhaps, MODS or RIS format could be built into the reference export list. 

Reference
https://www.zotero.org/support/dev/exposing_metadata

PS. Ironically Zotero's official website does not use native webpage citations.

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/9b43a385a7051902e02232439596ff4d004aeb7a

**Comment by pbstudent** [comment]
Andrew,

Voyant Tools 2.6.3 referencing works great with Zotero 6.0.21


It is interesting that citation styles are not listed in alphabetical order; perhaps in order of importance?

Thank you very much.

Cheers,
Steve
