### ISSUE TITLE
Chinese corpus shows "," character as a keyword

### ISSUE THREAD

**Issue by bobatrance** [voyanttools/Voyant#42]
I've attempted to use a Chinese corpus to do some analysis. However, the tools shows the "," as a frequent item. However, it is not merely a comma, it appears to associate it with random Chinese characters. See the attached image, when selecting that character (circled in red), it highlights various random characters.

![image](https://user-images.githubusercontent.com/596512/204971961-04e535ea-4baa-4fdd-a29e-eb0a7b972bb7.png)

Is there a way to blacklist this odd character? Maybe there is some kind of processing I can do, eg. use a different character encoding on the text before pasting it in? 

Thanks!

**Comment by ajmacdonald** [comment]
You can create a set of custom stopwords. See the docs for more info: https://voyant-tools.org/docs/#!/guide/stopwords

**Comment by bobatrance** [comment]
Thanks for the suggestion. When I try to put in both the english comma "," and/or the chinese comma "，" as a stopword, the issue still persists and messes up the analysis.

Interestingly though, if I strip the text of any and all punctuation marks, the text is parsed correctly. However, it's quite annoying to go back and reference the document when it is devoid of punctuation. Could there be some issue with the full-width characters?

**Comment by ajmacdonald** [comment]
Can you please retry uploading your corpus, but use the options to set the text language to Chinese?
There may be an issue with the automatic language detection code.

![image](https://user-images.githubusercontent.com/882444/205978792-0362dd1b-be03-48e6-b684-5246797cf68f.png)

**Comment by ajmacdonald** [comment]
Hello @bobatrance , were you able to resolve your issue?

**Comment by bobatrance** [comment]
Hi, it looks like the most recent build that's being hosted shows no issues when I change the processing manually to Chinese. Thanks very much! I'm curious to know what was causing the parsing error?

**Comment by ajmacdonald** [comment]
The library that we're using for language detection is not great at handling Chinese.

I tested with this file: [tao te ching.txt](https://github.com/voyanttools/Voyant/files/10501169/tao.te.ching.txt)
It was detected as `zh-tw` (Chinese - Traditional, Taiwan), and included the error you described.
Manually setting it to Chinese in the Voyant options forces `cn` (Chinese - Simplified, People's Republic of China), which then removes the error.
I don't know Chinese so I have no idea which is correct.
