### ISSUE TITLE
Documents filtered on a term display

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/Voyant#45]
Documents panel
Using a term such as,

Sinclair, S. & G. Rockwell. (2022). Documents. Voyant Tools. Retrieved December 5, 2022, from https://voyant-tools.org/?query=format*&corpus=067ee494bb8319c530da25e2a6c177e4&view=Documents

does not include count as per image:
![Screenshot 2022-12-05 at 12-03-24 Voyant Tools](https://user-images.githubusercontent.com/24277755/205629085-6df74d31-f85f-429b-b45a-6d546f8195f6.png)

In addition, the export of current view provides correct data from panel display but all data export returns data from original default collection.

**Comment by ajmacdonald** [comment]
This will fix the count not updating: https://github.com/voyanttools/Voyant/commit/d8e9903534c6a7a8a0f08e4d5ee8262f5d5da39e

**Comment by ajmacdonald** [comment]
Exporting all data is supposed to return the original data, unless I'm not understanding what you're saying.

**Comment by pbstudent** [comment]
The logic of panel exports is to move viewed panel data to export which has two options - panel view and all available data that maybe the same or different depending on length of viewable data. If I have a context for one term, I get all the data for that term, rather than returning to default data view. If I have a term view for documents I would expect to have only all available data for that term view in documents panel, even if it is the same as panel display. That appears to be the logic of workflows as I understand for Voyant Tools. However, if there is a different workflow then it could be useful to have the logic / workflow included in the help, assuming it is not already articulated in the help - https://voyant-tools.org/docs/#!/guide .
Thanks.

**Comment by ajmacdonald** [comment]
Ah I see what you're saying now. I'm creating a separate issue to track it.

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/issues/46
