### ISSUE TITLE
Collocations window limits items

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/Voyant#49]
Sample: https://voyant-tools.org/?corpus=067ee494bb8319c530da25e2a6c177e4&query=format*&view=CorpusCollocates

Scrolling to the end of the window does not reveal the remainder of the data. Only export of all data obtains the full list of collocates.

Can the interactive window display the full list?

**Comment by ajmacdonald** [comment]
Thanks for finding this.
It's been fixed in the code and will be available in the next server update.
https://github.com/voyanttools/trombone/commit/447c89f9a0aa59520a74fc781639258a08dd84e9
