### ISSUE TITLE
poetry corpus XML

### ISSUE THREAD

**Issue by alhuber1502** [voyanttools/Voyant#51]
There appear to be some display issues (in the Reader tool) when uploading TEI/XML-encoded poems, e.g. [this poem](https://www.thomasgray.org/texts/poems/txt_GrayTh1716_welcc.xml) appears like [this](https://voyant-tools.org/?corpus=78c881a12fca185bbd26b8f449d8b8aa) in the Reader:

1. the text appears as prose, not formatted in line groups `<lg>` and lines `<l>` as in the source,
2. there seems to be no option to filter/separate out any `<note>`s (they appear inline with the text),
3. when scrolling to the bottom of the text, the Reader app appears to break;

Thanks!

**Comment by ajmacdonald** [comment]
The Reader isn't meant to be a full fledged XML (or HTML) viewer; it preserves `<div>` and `<p>` tags but strips the rest.

Voyant has a specialized reading environment called the Dynamic Table of Contexts which preserves all tags and will apply any CSS that's linked in the XML file. The only catch is the CSS file needs to be hosted somewhere accessible. It can also handle notes using the "curator mode" to specify the usage of the `<note>` tag.
Once you've uploaded a corpus, simply add `/dtoc/` to the URL to access the Dynamic Table of Contexts, e.g. https://voyant-tools.org/dtoc/?corpus=78c881a12fca185bbd26b8f449d8b8aa&curatorId=1680711133200.6188 (NB: I've performed the curation to handle notes, which is stored using the curatorId in the URL).
There is some documentation regarding DToC here: https://cwrc.ca/Documentation/public/DITA_Files-Various_Applications/DToC/OverviewDToC.html

I'll investigate what's making the Reader appear to break when scrolling.

**Comment by alhuber1502** [comment]
Thanks!  I didn't know about DToC, which sounds useful.  It would still be great to see at least a few more essential tags like `<l>`, `<lg>` recognized as block-level elements in the display simply to make it usable for poetic texts.

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/trombone/issues/23

**Comment by ajmacdonald** [comment]
This commit addresses issue 3: https://github.com/voyanttools/Voyant/commit/847551951dcb9982c6c6cdba4e7f95078d6d83f9

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/trombone/commit/d3dddecf070c4569e48149129ab93c742f19f68e

**Comment by ajmacdonald** [comment]
Issues 1 and 3 have been addressed and are part of the most recent update to the server. Issue 2 won't be fixed as it's beyond the scope of the Reader (use DToC for that).

**Comment by alhuber1502** [comment]
Fabulous, thank you so much!
