### ISSUE TITLE
Spyral: selecting a single (or group of) document(s) from a corpus?

### ISSUE THREAD

**Issue by alhuber1502** [voyanttools/Voyant#53]
Sorry for this basic issue (just getting started with Spyral), but having looked through the docs for an example I have come up empty-handed.  I am trying to select a single (or group of) document(s) from a corpus to process further (e.g. use tools on, etc.).  

My possibly naive attempts have included (but I'm probably on the wrong track):

`my_corpus.documents( {docIndex:5} ).finally( this.tool( "reader" ) )`
or
`my_corpus.documents( {docId:"tgaen-tagtr"} ).finally( this.assign( "text5" ) )`

I'd appreciate if you could point me in the right direction (or part of the documentation with an example).  Many thanks!

**Comment by ajmacdonald** [comment]
Hello Alexander,

If you want to work with specific documents in a Voyant tool you can generally do that by specifying the `docIndex` or `docId` in the tool options, e.g. `loadCorpus( 'austen' ).tool( 'DocumentTerms', {docIndex: 3} )`. (You can also use an array of indexes/IDs to specify multiple documents.)
Note that this isn't universal. The Reader tool doesn't have handling for `docIndex` or `docId`, for example.
There is some documentation about the list of tools you can call as well as the parameters they accept here: https://voyant-tools.org/docs/#!/api/Spyral.Corpus-method-tool

If you want to assign document text(s) to a variable, you can do something like
```
loadCorpus( 'austen' ).texts( {docIndex: [3,5]} ).then( (textsArray) => {
  // do something with the arrray of document texts
})
```

For now, the `assign` method is only usable on corpora.

Please let me know if you have any more questions/issues.

**Comment by alhuber1502** [comment]
Perfect.  That's really helpful, thanks!
