### ISSUE TITLE
Spyral: TermsBerry tool has stopped working

### ISSUE THREAD

**Issue by alhuber1502** [voyanttools/Voyant#54]
`my_corpus.tool('TermsBerry')` produces an empty screen.

**Comment by alhuber1502** [comment]
It appears blank initially, but shows up when the Scaling is adjusted...

**Comment by ajmacdonald** [comment]
Thanks for finding this. I'm closing this issue in favour of [this one](https://github.com/voyanttools/trombone/issues/24) describing the root cause.
