### ISSUE TITLE
java.lang.NullPointerException on voyant-tools.org

### ISSUE THREAD

**Issue by AkliOnet** [voyanttools/Voyant#57]
hi, if one can help me understand what cause this error, here is the corpus : https://voyant-tools.org/?corpus=fa14417bf765f4190b15edbeb83a1ef1

the tool concerned are context, microsearch and  wordtree (the best tools)

**Comment by ajmacdonald** [comment]
Hi, please email me at voyanttools@gmail.com and I'll try to help you solve this issue.
