### ISSUE TITLE
Corpus Summary Export

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/Voyant#60]
No CSV export for Summary, only view the entire display and copy/paste to text file.

**Comment by ajmacdonald** [comment]
The Summary panel combines data from many different tools. What would you expect a CSV export of it to look like?

**Comment by pbstudent** [comment]
This corpus has 25 documents with 43,756 total words and 3,923 unique word forms. Created now.
Document Length:

    Longest: Open University of Tanzan… (5531); Kwame Nkrumah University… (4427); Africa Nazarene Universit… (3872); Tamil Nadu Open Universit… (3357); Open University of Sri… (2657)
    Shortest: Central Virginia Communit… (98); Northern Virginia Communi… (338); Universität Hamburg… (361); African Virtual Universit… (619); Washington State Universi… (743)

Vocabulary Density:

    Highest: Central Virginia Communit… (0.694); Northern Virginia Communi… (0.565); Universität Hamburg… (0.504); African Virtual Universit… (0.472); Washington State Universi… (0.416)
    Lowest: Open University of Tanzan… (0.251); Kwame Nkrumah University… (0.260); The University of the… (0.267); Africa Nazarene Universit… (0.270); Southern Alberta Institut… (0.277)

Average Words Per Sentence:

    Highest: Wawasan Open University… (151.1); Queensland University… (72.6); Open University of Sri… (50.1); Washington State Universi… (49.5); University of Kelaniya… (45.8)
    Lowest: Universität Hamburg… (20.1); Odisha State Open Univers… (21.8); African Virtual Universit… (22.9); Technical University… (23.3); University of Leeds OER (23.5)

Readability Index:

    Highest: Northern Virginia Communi… (18.584); University of Edinburgh… (17.908); Queensland University… (17.490); Central Virginia Communit… (17.374); Wawasan Open University… (16.355)
    Lowest: The University of the… (13.578); African Virtual Universit… (13.669); Universität Graz OER… (13.734); University of Kelaniya… (13.772); SRI Ramachandra Institute… (14.046)

Most frequent words in the corpus: oer (845); university (505); open (485); resources (351); policy (337)
Distinctive words (compared to the rest of the corpus):

 1;  Africa Nazarene Universit…: anu (31), nazarene (10), africa (13), idl (7), designer (7).
 2;  African Virtual Universit…: avu (13), file (4), languages (3), formats (6), african (4).
 3;  Central Virginia Communit…: hb (2), virginia (2), college (3), cvcc (1), 454 (1).
 4;  Glasgow Caledonian Univer…: gcu (11), gcu.ac.uk (3), oers (19), clearly (3), licence (11).
 5;  Kwame Nkrumah University…: knust (61), dr (17), ghana (14), africa (19), michigan (10).
 6;  Netaji Subhas Open Univer…: nsou (9), subhas (3), netaji (3), kolkata (2), studies (3).
 7;  Northern Virginia Communi…: faq (3), vccs (2), 212p (2), college (3), faculty (6).
 8;  Odisha State Open Univers…: odisha (15), state (17), unported (7), cemca (7), supported (7).
 9;  Open University of Sri…: ousl (66), vv (8), memo (8), 378th (7), 378 (7).
10; Open University of Tanzan…: tanzania (20), strategies (24), statement (22), ict (14), odl (12).
11; Queensland University…: qut (23), mopp (4), visitors (3), records (3), achievement (2).
12; SRI Ramachandra Institute…: sriher (10), nroer (9), quadrant (5), licensees (4), contains (3).
13; Southern Alberta Institut…: sait (12), ac (12), sait’s (10), 2.21.1 (8), instructors (12).
14; Tamil Nadu Open Universit…: tamil (46), nadu (46), tnou (31), qrb (7), institutional (20).
15; Technical University…: graz (34), tu (18), rl (6), oerp (6), 94000 (6).
16; The University of the…: value (7), pacific (5), figure (4), annex (5), shall (17).
17; Universität Graz OER…: graz (13), employees (5), oers (15), qualification (2), offers (4).
18; Universität Hamburg…: reutlingen (6), zoerr (2), processing (2), enables (2), www.unesco.de (1).
19; University of Edinburgh…: edinburgh (8), uk (3), collections (4), oers (19), position (5).
20;  University of Kelaniya…: kelaniya (15), board (23), shall (35), faculty (26), clearance (6).
21;  University of Leeds OER: leeds (6), deposited (4), exceptional (3), oers (16), library.leeds.ac.uk (2).
22;  Uttarakhand Open Universi…: uttarakhand (5), shall (20), contents (9), phase (3), oppourtinities (2).
23;  Washington State Universi…: wsu (8), faculty (14), developer (4), zero (2), wishing (2).
24;  Wawasan Open University…: wou (17), assistant (6), integration (14), sc (7), steering (4).
25;  Zurich University of…: zhaw (11), german (6), 1.0.3 (4), 03 (4), von (3).

**Comment by pbstudent** [comment]
Sample [latest corpus copy.ods](https://github.com/voyanttools/VoyantServer/files/8018959/latest.corpus.copy.ods)

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/9aecfa9701327d5d2b506fefc74d9ba161f7819f

**Comment by pbstudent** [comment]
Thank you for all of the fixes and features.
Sincerely,
Steve
