### ISSUE TITLE
Collocates - Export all available data returns webpage with headers

### ISSUE THREAD

**Issue by pbstudent** [voyanttools/Voyant#61]
https://voyant-tools.org/?corpus=227a53512abde752f3fa7ada7595bc36

Corpus Collocates export of all data was a webpage with the following headers without data:
Term	Frequency	Context	ContextualFrequency

Export page URL:
https://voyant-tools.org/trombone?start=0&template=corpuscollocates2tsv&outputFormat=text&tool=corpus.CorpusCollocates&forTool=corpuscollocates&withDistributions=true&corpus=227a53512abde752f3fa7ada7595bc36&query=oer&query=open&query=university&query=resources&query=policy&query=educational&query=use&query=learning&query=materials&query=license&stopList=auto&context=5&palette=default&categories=auto&view=corpusset&panels=cirrus%2Creader%2Ctrends%2Csummary%2Ccontexts&suppressTools=false

**Comment by ajmacdonald** [comment]
Thanks for finding this!
https://github.com/voyanttools/trombone/commit/648262669801a197f58e6a4948a379ac35bc545c
