### ISSUE TITLE
Voyant-tools.org is redirecting guide options to apache Tomcat 9 page

### ISSUE THREAD

**Issue by Otgomtol** [voyanttools/Voyant#7]
HI support team, Yesterday I sent a tweet as folows: It is happening to all refereenced guide's option in Voyant-tolls.org
Otavio Tolentino
@otgomtol
@VoyantTools
 Congrats for this great tool an for refreshing application access. I would like to report error addressing https://voyant-tools.org/docs/#!/guide/ it is rediretcting to Apache Tomcat 9 site and not to Voyant-tools guide page. It would help a lot if could be corrected.
8:47 PM · 7 de jan de 2022·Twitter Web App

Check the URL in the command line of the image below and that response is from Tomcat. 
![image](https://user-images.githubusercontent.com/97340367/148642244-fcbc5d3a-79d7-4209-867f-12cc91d7e527.png)

Contact me for any question.

Otavio Tolentino

**Comment by ajmacdonald** [comment]
Thank you for reporting this Otavio. It has now been fixed.
