### ISSUE TITLE
Spyral Catalogue should have a "Create New Notebook" button in lower right.

### ISSUE THREAD

**Issue by GeoffreyRockwell** [voyanttools/Voyant#70]
Spyral Catalogue should have a "Create New Notebook" button in lower right so that you don't just choose items, but can create a new one.

**Comment by ajmacdonald** [comment]
There is one in the top right already; it's the + icon. Do you think we should relocate it?

**Comment by GeoffreyRockwell** [comment]
No, it should stay in the top right, but when you open the Catalogue there should also be a button to create a new notebook in the Catalogue. I would suggest a button down next to "Cancel".

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/d92b7a74231531a03369fcbabba8eedadd978e7d
