### ISSUE TITLE
Catalogue Improvements

### ISSUE THREAD

**Issue by GeoffreyRockwell** [voyanttools/Voyant#71]
It is hard to find my own notebooks in the Catalogue if I haven't included them in the Public Catalogue. There should be a way to see my own notebooks even if they aren't in the Public Catalogue. Perhaps, by default, the list of Notebooks in the middle could be those I have have authored in reverse chronological order (most recent edits first.)

**Comment by ajmacdonald** [comment]
Once signed in, the list of all the user's notebooks is available by clicking on the account icon.
Do you think that is sufficient?

**Comment by GeoffreyRockwell** [comment]
Thanks. I just saw it. It works well - just what I was looking for. 

A side of me still wonders if it should all be in one place. Let’s leave it for now.

Geoffrey R.
