### ISSUE TITLE
Scrolling Up In List of Entities

### ISSUE THREAD

**Issue by learnspyral** [voyanttools/Voyant#74]
When I run the NSSI NER on the Frankenstein text and the try to explore the 87 locations I can scroll down but not up. If I go to the bottom and then try to scroll up it starts to flickr and I never seem to get to the top again. See:

https://voyant-tools.org/?corpus=frank&view=Reader

Run the NSSI NER and then open the list of Locations and scroll down to bottom. Then try to get to the top.

**Comment by ajmacdonald** [comment]
Note to self: issue seems to be caused by tags sneaking through into entity term info

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/trombone/commit/313bc29fec92f9aad605489a194e0f1bd320e341
