### ISSUE TITLE
Group By when loading from a CSV

### ISSUE THREAD

**Issue by learnspyral** [voyanttools/Voyant#76]
Is it possible to provide a column that could be used to group items in a table by. Thus one could have, for example, a keyword column. There might be three different keywords. All the rows that have the keyword "main" would be grouped into one document and so on. This would work like GroupBy in loading XML.

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/5baece837d0ed3ffe66a02523185d93db2d28b0a
https://github.com/voyanttools/trombone/commit/055eb3cadfceb729eb8306a3cbecf73852d05129
