### ISSUE TITLE
Cirrus parameters

### ISSUE THREAD

**Issue by learnspyral** [voyanttools/Voyant#78]
I don't seem to get 5 words in Cirrus when I set the parameter limit or visible to 5. See code here: 

https://voyant-tools.org/spyral/learnspyral@gh/cirrus/

myCorpus.tool("Cirrus", 
	{limit: 5, //limit the number of terms shown
    visible: 5, //limit the number of terms shown
    withDistributions: "raw", //change from the default relative to raw
    docIndex: 0, //indicate the document you wish to analyze 
    stopList: "it, and, the" //define a custom stop-word list as a comma separated list
    });

**Comment by ajmacdonald** [comment]
It's working for me.
`limit` sets the maximum possible limit in the Terms slider
`visible` sets the initial value for the above limit

There are some hard coded values that may be messing things up. The minimum value for the slider is 25 and can't be changed.

Note to self: https://github.com/voyanttools/Voyant/blob/master/src/main/webapp/app/panel/Cirrus.js#L170-L182

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/eb75d0487708808cf93b7ff88e7acf88897a3e97
