### ISSUE TITLE
https://voyant-tools.org/ is down

### ISSUE THREAD

**Issue by Otgomtol** [voyanttools/Voyant#8]
I have been trying many times to access https://voyant-tools.org/ but unfortunatelly it is down.

So please, let us know when it will available again. 

Thanks,

Otavio Tolentino

**Comment by ajmacdonald** [comment]
Hello Otavio,
Thank you for bringing this to my attention. I've restarted the server and it is up again.
Apologies for the disruptions. We have recently migrated to a different server and it appears there are some configuration issues still.
