### ISSUE TITLE
Trends bars are all same colour

### ISSUE THREAD

**Issue by learnspyral** [voyanttools/Voyant#83]
When we choose to only graph one document in a corpus and we have Trends set to show bars, the bars are all the same blue. 

See https://voyant-tools.org/spyral/learnspyral@gh/ToolSummary/

If I comment out the docIndex and bins then I get different colours.

Why can't the colours of the bars be different even when doing one document.

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/653c7edd55ce16c7b1c6ea778b17bf098873d5a5
