### ISSUE TITLE
Capitalization of "frequencies" in Options of Trends

### ISSUE THREAD

**Issue by learnspyral** [voyanttools/Voyant#84]
In the Trends tool, if I pick Options, I get a dialog box. The label "frequencies" should be capitalized like the other labels.

**Comment by ajmacdonald** [comment]
Note to self: much of the localization for this tool is hardcoded

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/0b9df1373fefc858a764b2b65115ac0d2ed65742
