### ISSUE TITLE
Spyral: programmatically specify visible columns for table based tools

### ISSUE THREAD

**Issue by learnspyral** [voyanttools/Voyant#87]
Can I use code to add the Significance column to the Documents Terms tool when it is called in Spyral. Also, can I have the table sorted by Significance. See cell 12 in: https://voyant-tools.org/spyral/learnspyral@gh/IRCCProjects/ 
I'm trying to call the Document Terms tool and have them sorted by significance.

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/5db2ff997050e2748ff10d3cad9b04c270dbea1e
