### ISSUE TITLE
Server https://voyant-tools.org/ is down

### ISSUE THREAD

**Issue by Otgomtol** [voyanttools/Voyant#9]
Hi Support Team,
Sorry to report but Server https://voyant-tools.org/ is down again.
I would like to thank you for the prompt response about the last issue, on the same subject, reported few days ago.
Appreciate you could check this instabillity to solve it to be stable and reliable to last more time.
Thanks in advance.Otavio Tolentino.

**Comment by ajmacdonald** [comment]
Hi Otavio,
Thanks again. I'm hard at work trying to track down the cause. In the meantime I've restarted the server.
If this happens again, feel free to email instead of creating a new issue. The Voyant Tools email is: voyanttools at gmail dot com

Kind regards,
Andrew
