### ISSUE TITLE
Three things for Document Terms: 1) Not sorting on tf-idf 2) Scale shows all documents and 3) how to get column to show

### ISSUE THREAD

**Issue by learnspyral** [voyanttools/Voyant#91]
1) When I generate a Document Terms tool in Spyral and specify the document and that it should be sorted on "tf-idf", I don't get the words sorted properly. Here is the code:

> theDocument = "0";
> myCorpus.tool("DocumentTerms", {docIndex: theDocument, sort: "tfidf", style: "width:600px; height:350px"});

This is in notebook: https://voyant-tools.org/spyral/learnspyral@gh/IRCCProjects/ 

2) When I click on the Scale button it shows that all documents are selected when my code says docIndex = 0 . It should show the other documents deselected.

3) How can I force the Significance (or other) column to show when using code to generate a tool panel.

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/cab4e1c40fa8bf3eed98ad28dfdcb1f0fc6a25fc

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/909dd7e741b0c929692f98d442fb8f9036640e04
