### ISSUE TITLE
Formatting Text Cell doesn't work as expected

### ISSUE THREAD

**Issue by learnspyral** [voyanttools/Voyant#93]
When I'm entering a new text cell I like to start with a heading. If I place my cursor in the new text cell and pick Heading 2 from Format I expect the text I type to be in Heading 2, but it isn't. I get normal text. 
If I look at the raw code there is an H2 element, but further down from where my cursor is and hard to access in WYSIWG mode.

**Comment by ajmacdonald** [comment]
Note to self: an issue with Chrome on Mac and Windows

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/ecab87816a0c857e3aa367e0a6c1a6d33adb4459
