### ISSUE TITLE
Trend doesn't show up in Correlations

### ISSUE THREAD

**Issue by learnspyral** [voyanttools/Voyant#97]
If I call up the Correlations display there are two columns that are supposed to show sparklines for the two terms. The sparklines don't show. See

https://voyant-tools.org/?corpus=austen&view=correlations

See the documentation:
https://voyant-tools.org/docs/#!/guide/correlations
It says "Trends: two sparklines (mini graphs) that show the distribution of relative frequencies (the left one is for Term 1 and the right one is for Term 2)"

**Comment by ajmacdonald** [comment]
https://github.com/voyanttools/Voyant/commit/ec9a77a222089e8c9a5069cf0fec0293ec9e62d6
